// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: FirebaseKeys.devWebApiKey, // use dev or prod here
    appId: '1:834916158321:web:36bc864b298d74247fc4d0',
    messagingSenderId: '834916158321',
    projectId: 'task-management-1455a',
    authDomain: 'task-management-1455a.firebaseapp.com',
    databaseURL: 'https://task-management-1455a-default-rtdb.firebaseio.com',
    storageBucket: 'task-management-1455a.firebasestorage.app',
    measurementId: 'G-XE2CRS4KXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: FirebaseKeys.devAndroidApiKey,
    appId: '1:834916158321:android:65bfd1181e8cfe617fc4d0',
    messagingSenderId: '834916158321',
    projectId: 'task-management-1455a',
    databaseURL: 'https://task-management-1455a-default-rtdb.firebaseio.com',
    storageBucket: 'task-management-1455a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: FirebaseKeys.devIosApiKey,
    appId: '1:834916158321:ios:4257c04ec4c5d2f87fc4d0',
    messagingSenderId: '834916158321',
    projectId: 'task-management-1455a',
    databaseURL: 'https://task-management-1455a-default-rtdb.firebaseio.com',
    storageBucket: 'task-management-1455a.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );
}